# This workflow will build and upload WMCore core services to the production PyPI
# based on tag releases, see build_and_publish_services job. Then, the second
# named build_images, will build appropriate docker images using CMSKubernetes
# Dockefiles and upload them to CERN registry.
#
# The build_and_publish_services job relies on pypi_build_template.yaml
# The build_images relies on docker_images_template.yaml template
# Each job use matrics target (as input list to iterate) and setup
# wmcore_component which is used by corresponding template to perform
# set of actions. We also define here necessary secrets used by given template.

on:
  # this section fires workflow on a specific tag which matches some pattern
  push:
    tags:
      - '*.*.*'
  # this section forces manual builds
  workflow_dispatch:
    inputs:
      name:
        description: 'WMCore services'

jobs:
  # docker images to CERN registry
  build_images:
    name: Build_images
    strategy:
      matrix:
        target: [reqmgr2ms-unmerged]
    uses: ./.github/workflows/docker_images_template.yaml
    with:
      wmcore_component: ${{ matrix.target }}
    secrets:
      cern_user: ${{ secrets.CERN_LOGIN }}
      cern_token: ${{ secrets.CERN_TOKEN }}
