# Reusable workflow to setup a specific WMCore component for pip
name: Build and publish package to TestPyPi

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_publish:
    name: Build and publish distribution package
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      #      url: https://test.pypi.org/p/example-package-amaltaro
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Upload package distributions to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          #          user: __token__
          #          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
